### ISSUE TITLE
Scale/alter for other size of ball

### ISSUE THREAD

**Issue by dwillmore** [ploopyco/adept-trackball#1]
I love this project.  I've wanted to make my own trackball for a long time.  I originally wanted to make one with an undrilled bowling ball, but I've never been able to source a ball without some kind of manufacturers logo engraved in it.  I have an old logitech trackball that I very gently nicked the ball by dropping it once, and I know how much even a tiny imperfection in the ball makes the experience unplesant.

But this seems quite reasonable (unlike my idea).  But, I'm in the USA and snooker isn't really a game here.  We have lots of billiards supplies, but the balls are 2.25".  Any suggestions on how I could go about adapting this design to accomodate the larger size of ball?  Naively, I could scale it up by 9/7 and try to adapt the remaining parts to fit, but that seems problematic as all the bearings, screws, switch mounts, etc. will not take kindly to that.

Thank you for everything!

**Comment by dwillmore** [comment]
Optionally, it seems like it's relatively easy to source a 1.75" steel bearing.  My concern would be that the surface would be too smooth to track--not that a little bit of sandpaper couldn't solve that in short order.  Anyone see concerns with the added mass/inertia of using a steel ball instead of a resin one?

**Comment by jwGreys** [comment]
I recently picked up a G100-1 Bearing off Amazon at 44.45mm (1.75") and so far it's working fairly well for me.  There was some skipping at first (on fast movements) but after it got smudged up with fingerprints a bit it has been a blessing for my personal preference.  The added mass really gives me a feeling of more control on the cursor.

**Comment by itsnoteasy** [comment]
I have managed to fit a 57.2mm ball to the adept stl. what i did was scaled the stl up in a 45:55 ratio. Then i took a 2mm drill bit and drilled three shallow holes beside the ball bearing mount. I then pressed in a 2.5mm zirconium bearing in each hole. I used the rp2040 trackball pcb by jfedor since i already had it, and hotglued it and switches into position.
