### ISSUE TITLE
invalid keyboard_folder value

### ISSUE THREAD

**Issue by omgitsraven** [ploopyco/adept-trackball#2]
I'm trying to follow the "QMK Firmware Programming" page on the wiki, but when I run:
```qmk compile -kb ploopyco/madromys/rev1_001 -km via```

it returns the following:
```qmk.exe compile: error: argument -kb/--keyboard: invalid keyboard_folder value: 'ploopyco/madromys/rev1_001'```

**Comment by itsnoteasy** [comment]
It compiles fine for me. try git pull to update your qmk installation and retry.

**Comment by omgitsraven** [comment]
That's what I was missing, thank you!
